apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-cgkzrtgo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-cgkzrtgo:5e6f0b7766b8b99d393614fd946e702cbac69e9e@sha256:5dfa1a1d40a738468ea07bcd822840f1750c663b42c49d82bb49c55c6dc3e9b7
          name: container-image
